version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/server
permissions:
  - object: /home/ubuntu/server
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: root
