ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:operation-http-request-title: Example Request
:operation-http-response-title: Example Response

[[resources]]
= Resources

[[resources-auth]]
== 회원가입/로그인

[[resources-auth-email]]
=== 이메일 체크
operation::auth/email[snippets='http-request,http-response,request-headers,request-fields,response-fields']

[[resources-auth-signup]]
=== 회원가입
operation::auth/signup[snippets='http-request,http-response,request-headers,request-fields,response-fields']

[[resources-auth-login]]
=== 로그인
operation::auth/login[snippets='http-request,http-response,request-headers,request-fields,response-fields']

[[resources-users]]
== 회원 관리

[[resources-user-find]]
=== 로그인 유저 조회
operation::users/me[snippets='http-request,http-response,request-headers,response-fields']

[[resources-user-update]]
=== 유저 정보 수정
operation::users/update[snippets='http-request,http-response,request-headers']

[[resources-user-delete]]
=== 유저 삭제
operation::users/delete[snippets='http-request,http-response,request-headers']


[[resources-trip]]
== 여행 일정 관리

[[resources-trip-create]]
=== 여행 일정 생성
operation::trip/create[snippets='http-request,http-response,request-headers,request-fields']

[[resources-trip-find-all]]
=== 내 모든 여행 일정 조회
operation::trip/find-all-my[snippets='http-request,http-response,request-headers,response-fields']

[[resources-trip-find-recent]]
=== 내 최근 여행 일정 조회
operation::trip/find-recent[snippets='http-request,http-response,request-headers,response-fields']

[[resources-trip-update]]
=== 여행 일정 수정
operation::trip/update[snippets='http-request,http-response,request-headers,path-parameters,request-fields']

[[resources-trip-delete]]
=== 여행 일정 삭제
operation::trip/delete[snippets='http-request,http-response,request-headers,path-parameters']

[[resources-trip-recommend]]
=== 여행 일정 추천
operation::trip/find-recommendation[snippets='http-request,http-response,request-parameters,response-fields']


[[resources-like]]
== 좋아요(찜) 관리

[[resources-like-create]]
=== 좋아요 생성
operation::trip/create[snippets='http-request,http-response,request-headers,request-fields']

[[resources-like-delete]]
=== 좋아요 취소
operation::like/delete[snippets='http-request,http-response,request-headers,request-fields']


