SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE user RESTART IDENTITY;
TRUNCATE TABLE trip RESTART IDENTITY;
TRUNCATE TABLE path RESTART IDENTITY;
TRUNCATE TABLE place RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;
